export const ARTICLES_FETCH_REQUEST = 'ARTICLES_FETCH_REQUEST';
export const ARTICLES_FETCH_SUCCESS = 'ARTICLES_FETCH_SUCCESS';
export const ARTICLES_FETCH_FAILURE = 'ARTICLES_FETCH_FAILURE';
export const ARTICLES_FETCH_EXIT = 'ARTICLES_FETCH_EXIT';
export const ARTICLES_SET_CURRENT_PAGE = 'ARTICLES_SET_CURRENT_PAGE';
export const ARTICLES_SORT_REQUEST = 'ARTICLES_SORT_REQUEST';

export const ARTICLES_SET_SORT_KEY_REQUEST = 'ARTICLES_SET_SORT_KEY_REQUEST';
export const ARTICLES_SET_SORT_KEY = 'ARTICLES_SET_SORT_KEY';
export const ARTICLES_SET_SORT_DIRECTION_REQUEST = 'ARTICLES_SET_SORT_DIRECTION_REQUEST';
export const ARTICLES_SET_SORT_DIRECTION = 'ARTICLES_SET_SORT_DIRECTION';
    

export const ARTICLES_CLEAR_PAGE_CACHE = 'ARTICLES_CLEAR_PAGE_CACHE';