export const ARTICLES_FETCH_REQUEST = 'ARTICLES_FETCH_REQUEST';
export const ARTICLES_FETCH_SUCCESS = 'ARTICLES_FETCH_SUCCESS';
export const ARTICLES_FETCH_FAILURE = 'ARTICLES_FETCH_FAILURE';
export const ARTICLES_SET_CURRENT_PAGE = 'ARTICLES_SET_CURRENT_PAGE';